name: 'Caginator'
description: 'Nicholas Cage your repository.'
author: 'TartanLlama'
inputs: 
  myToken:
    description: 'A token with access to your repository scoped in as a secret.'
runs:
  using: 'node12'
  main: 'lib/main.js'
